### ISSUE TITLE
Tie in with Contracts system

### ISSUE THREAD

**Issue by jwvanderbeck** [jwvanderbeck/TestFlight#10]
Make TestFlight create in game contracts to get a certain amount of FlightData for a part in a certain scope.  Assuming KCT integration happens, there would need to be a check that ensures this happens in flight and not in a sim.

**Comment by jrossignol** [comment]
Since FlightData is obviously a non-stock thing, youl'll want to check out the wiki page on [Extending Contract Configurator](https://github.com/jrossignol/ContractConfigurator/wiki/Extending).  I notice it's a bit out of date, so I'll have to go in there and do some updates (for sure before the 0.7.0 release).  Basic idea is you need to extend ParameterFactory for the Parameter "loader".  You can then use any parameter that extends the stock ContractParameter, although I'd recommend extending [ContractConfiguratorParameter](https://github.com/jrossignol/ContractConfigurator/blob/master/source/ContractConfigurator/ContractParameter/ContractConfiguratorParameter.cs), as it works around some stock issues (mainly the fact that any parameter that gets an exception on load/save prevents all other contracts from loading/saving.

The other thing to note is you should look at my dev branch if you're using any of the ConfigNodeUtil utility functions - I just did a refactor that changes the interface - if you use the main branch your stuff will be broken when I release 0.7.0 in a couple weeks.

I'll have to make a note to add KCT support in Contract Configurator itself - I imagine I could do a check in one or two global spots to prevent contracts from being met during a sim.

**Comment by jwvanderbeck** [comment]
Thanks for the input @jrossignol I shall do some reading :)

**Comment by jrossignol** [comment]
Oh, and the other thing I'd recommend is isolating your stuff that depends on Contract Configurator in a separate .dll (which it looks like you already generally do anyway).  That way if anything breaks because I made a thoughtless change or otherwise broke something it won't take down TestFlight entirely.  It also makes the Contract Configurator integration optional, if that's something you care to offer to your users as an option.

**Comment by jrossignol** [comment]
And one last thing, a couple good ParameterFactory examples are:
 * [HasAntennaFactory] (https://github.com/jrossignol/ContractConfigurator/blob/dev/source/CC_RemoteTech/HasAntennaFactory.cs) - For the RemoteTech integration, shows a bunch of the different validation functions in action.
 * [VesselNotDestrohyedFactory] (https://github.com/jrossignol/ContractConfigurator/blob/dev/source/ContractConfigurator/ParameterFactory/VesselNotDestroyedFactory.cs) - Simple example that shows loading repeated attributes in a config node into a list.

**Comment by jwvanderbeck** [comment]
Now that 0.7 of CC is out, this needs to move up the list.

**Comment by jwvanderbeck** [comment]
As of TestFlight 1.3, TF now supports ContractConfigurator by adding a new parameter for gathering flight data on a given part.
