### ISSUE TITLE
Make loss of thrust cause loss of Isp as well

### ISSUE THREAD

**Issue by jwvanderbeck** [jwvanderbeck/TestFlight#58]
see below

**Comment by jwvanderbeck** [comment]
> <ferram4> Agathorn, Isp = T / g * (C * A_e + 1) / (P_0 * A_e - T), where:
<ferram4> T is thrust
<ferram4> A_e is exit area
<ferram4> P_0 is ambient pressure
<ferram4> g is 9.81 m/s^2
<ferram4> C is a constant accounting for the exit Mach number (calculate from default stats)

**Comment by ferram4** [comment]
Technically, the 1 should be V_e, the velocity at the exit, so the equation should properly be:

Isp = T / g * (C * A_e + V_e) / (P_0 * A_e - T), where:
T is thrust
A_e is exit area
P_0 is ambient pressure
g is 9.81 m/s^2
C is a constant accounting for the exit Mach number (calculate from default stats)
V_e is the velocity at the exit, (calculate from default stats)

Two unknowns for each engine, but they can be calculated from the two data points at SL and vac that each engine has.  A_e will need to be inputted for each engine, but P_0 can be grabbed straight from the game.

**Comment by ferram4** [comment]
Okay, scratch that, I made a few more mistakes.

Actual equation is:

Isp = (T * V_e / g) * 1 / [T - A_e * (P_e - P_0)]

where:
T is thrust (kN), (known from configs)
V_e is nozzle exit velocity (m/s), (calculate from atmosphere curve)
g is 9.81 (m/s^2)
A_e is exit area (m^2), (known from configs, but will need to be added)
P_e is exit pressure (kPa), (calculate from atmosphere curve)
P_0 is ambient pressure (kPa), (known from flight scene / atmosphere curve)

Note that KSP returns atmospheric pressure in atms, and 1 atm = 101.325 kPa.
KSP uses kN as its default unit of force.  Ensure that your units are correct or bad things will likely happen.

Values of V_e should be checked against the value calculated by V_effective = Isp * g.  Numbers should be close, but not exact, since V_effective will include pressure effects, but V_e will not.  They should be in the mid 2000 m/s to high 3000 m/s range.

Values of P_e should be compared to P_0 and common sense; engines such as the F-1, H-1, LR-89, RD-107, RD-171, etc, should have P_e very close to, perhaps only slightly less than, P_0, since these engines are designed for SL performance.  Engines such as the RD-58, RL-10, J-2, LR-105, AJ-10, etc. should have P_e << P_0, as they are vacuum-optimized engines, and so don't have to overpower 1 atm of backpressure.

**Comment by jwvanderbeck** [comment]
Depends on: https://github.com/NathanKell/ModularFuelSystem/issues/85

**Comment by jwvanderbeck** [comment]
No longer an issue as of KSP 1.0
